## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(["EIN", "NAME"], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
print(application_df.nunique())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df["APPLICATION_TYPE"].value_counts()
print(application_counts)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df["CLASSIFICATION"].value_counts()
print(classification_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_count2 = classification_counts.loc[classification_counts > 1]
print(class_count2)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 1800].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_df = pd.get_dummies(application_df)
numeric_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = numeric_df["IS_SUCCESSFUL"]
X = numeric_df.drop(["IS_SUCCESSFUL"],axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
# Get shape for input dimensions
inputs = X_train_scaled.shape[1]

## Use Auto Optimization to get the best Model

In [13]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=10,
        step=2), activation=activation, input_dim=inputs))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=10,
            step=2),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [14]:
!pip install keras-tuner

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting keras-tuner
  Downloading keras_tuner-1.3.5-py3-none-any.whl (176 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.1/176.1 kB 3.7 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (23.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.27.1)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.4)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.3.5 kt-legacy-1.0.5

In [15]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

In [16]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 60 Complete [00h 01m 23s]
val_accuracy: 0.7306122183799744

Best val_accuracy So Far: 0.7327113747596741
Total elapsed time: 00h 41m 29s

In [17]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'relu',
 'first_units': 7,
 'num_layers': 2,
 'units_0': 9,
 'units_1': 3,
 'units_2': 9,
 'units_3': 9,
 'units_4': 3,
 'units_5': 1,
 'tuner/epochs': 20,
 'tuner/initial_epoch': 7,
 'tuner/bracket': 2,
 'tuner/round': 2,
 'tuner/trial_id': '0043'}

In [18]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5554 - accuracy: 0.7327 - 699ms/epoch - 3ms/step
Loss: 0.5553647875785828, Accuracy: 0.7327113747596741

In [19]:
# Export our model to HDF5 file
best_model.save("AlphabetSoupCharity_Optimization.h5")

## Try More Parameters

In [20]:
# Still not at 75% accuracy, so test initial Starter Code model using activation 'Sigmoid' instead of 'relu' to see if that makes a difference

In [21]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
inputs = X_train_scaled.shape[1]
hidden_layer1 = 80
hidden_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=inputs, activation="sigmoid"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer2, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 80)                3520

 dense_5 (Dense)             (None, 30)                2430

 dense_6 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [22]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [23]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.5975 - accuracy: 0.7039
Epoch 2/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5727 - accuracy: 0.7204
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5682 - accuracy: 0.7234
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5626 - accuracy: 0.7262
Epoch 5/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5587 - accuracy: 0.7266
Epoch 6/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5558 - accuracy: 0.7281
Epoch 7/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5542 - accuracy: 0.7281
Epoch 8/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5534 - accuracy: 0.7292
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5520 - accuracy: 0.7287
Epoch 10/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5514 - accuracy: 0.7303
Epoch 11/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5505 - accuracy: 0.7306
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5497 - accuracy: 0.7299
Epoch 13/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5493 - accuracy: 0.7297
Epoch 14/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5490 - accuracy: 0.7309
Epoch 15/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5480 - accuracy: 0.7316
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5478 - accuracy: 0.7303
Epoch 17/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5476 - accuracy: 0.7320
Epoch 18/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5469 - accuracy: 0.7317
Epoch 19/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5456 - accuracy: 0.7314
Epoch 20/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5458 - accuracy: 0.7328
Epoch 21/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5457 - accuracy: 0.7330
Epoch 22/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5454 - accuracy: 0.7316
Epoch 23/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5450 - accuracy: 0.7321
Epoch 24/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5448 - accuracy: 0.7321
Epoch 25/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5448 - accuracy: 0.7332
Epoch 26/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5444 - accuracy: 0.7332
Epoch 27/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5441 - accuracy: 0.7336
Epoch 28/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5436 - accuracy: 0.7338
Epoch 29/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5439 - accuracy: 0.7331
Epoch 30/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5434 - accuracy: 0.7330
Epoch 31/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5431 - accuracy: 0.7354
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5430 - accuracy: 0.7339
Epoch 33/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5426 - accuracy: 0.7344
Epoch 34/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5429 - accuracy: 0.7347
Epoch 35/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5424 - accuracy: 0.7358
Epoch 36/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5421 - accuracy: 0.7351
Epoch 37/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5422 - accuracy: 0.7346
Epoch 38/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5420 - accuracy: 0.7350
Epoch 39/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5418 - accuracy: 0.7357
Epoch 40/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5415 - accuracy: 0.7352
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5415 - accuracy: 0.7352
Epoch 42/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5413 - accuracy: 0.7362
Epoch 43/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5412 - accuracy: 0.7355
Epoch 44/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5410 - accuracy: 0.7356
Epoch 45/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5406 - accuracy: 0.7363
Epoch 46/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5406 - accuracy: 0.7366
Epoch 47/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5407 - accuracy: 0.7365
Epoch 48/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5405 - accuracy: 0.7364
Epoch 49/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5405 - accuracy: 0.7364
Epoch 50/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5402 - accuracy: 0.7366
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5397 - accuracy: 0.7359
Epoch 52/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5400 - accuracy: 0.7355
Epoch 53/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5394 - accuracy: 0.7370
Epoch 54/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5395 - accuracy: 0.7361
Epoch 55/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5394 - accuracy: 0.7372
Epoch 56/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5391 - accuracy: 0.7362
Epoch 57/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5390 - accuracy: 0.7369
Epoch 58/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5389 - accuracy: 0.7381
Epoch 59/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5388 - accuracy: 0.7372
Epoch 60/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5385 - accuracy: 0.7363
Epoch 61/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5384 - accuracy: 0.7379
Epoch 62/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5384 - accuracy: 0.7369
Epoch 63/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5384 - accuracy: 0.7377
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5381 - accuracy: 0.7374
Epoch 65/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5380 - accuracy: 0.7370
Epoch 66/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5381 - accuracy: 0.7375
Epoch 67/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5377 - accuracy: 0.7372
Epoch 68/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5374 - accuracy: 0.7378
Epoch 69/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5373 - accuracy: 0.7379
Epoch 70/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5374 - accuracy: 0.7378
Epoch 71/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5373 - accuracy: 0.7382
Epoch 72/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5369 - accuracy: 0.7376
Epoch 73/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5371 - accuracy: 0.7384
Epoch 74/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5367 - accuracy: 0.7376
Epoch 75/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5369 - accuracy: 0.7373
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7383
Epoch 77/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5369 - accuracy: 0.7372
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5367 - accuracy: 0.7376
Epoch 79/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5365 - accuracy: 0.7391
Epoch 80/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7383
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5360 - accuracy: 0.7377
Epoch 82/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5361 - accuracy: 0.7385
Epoch 83/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7383
Epoch 84/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5361 - accuracy: 0.7375
Epoch 85/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5360 - accuracy: 0.7386
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.7379
Epoch 87/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5359 - accuracy: 0.7386
Epoch 88/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.7376
Epoch 89/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7385
Epoch 90/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5357 - accuracy: 0.7386
Epoch 91/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5356 - accuracy: 0.7395
Epoch 92/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5354 - accuracy: 0.7387
Epoch 93/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5355 - accuracy: 0.7382
Epoch 94/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7391
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5349 - accuracy: 0.7387
Epoch 96/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5353 - accuracy: 0.7395
Epoch 97/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5353 - accuracy: 0.7385
Epoch 98/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5349 - accuracy: 0.7401
Epoch 99/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5349 - accuracy: 0.7392
Epoch 100/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7380

In [24]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5573 - accuracy: 0.7264 - 589ms/epoch - 2ms/step
Loss: 0.5573191046714783, Accuracy: 0.7264139652252197

In [25]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
# Try adding a few more layers

inputs = X_train_scaled.shape[1]
hidden_layer1 = 80
hidden_layer2 = 30
hidden_layer3 = 15
hidden_layer4 = 8

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=inputs, activation="sigmoid"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer2, activation="sigmoid"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer3, activation="sigmoid"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer4, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_7 (Dense)             (None, 80)                3520

 dense_8 (Dense)             (None, 30)                2430

 dense_9 (Dense)             (None, 15)                465

 dense_10 (Dense)            (None, 8)                 128

 dense_11 (Dense)            (None, 1)                 9

=================================================================
Total params: 6,552
Trainable params: 6,552
Non-trainable params: 0
_________________________________________________________________

In [26]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [27]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 4ms/step - loss: 0.6268 - accuracy: 0.6634
Epoch 2/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5762 - accuracy: 0.7275
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5702 - accuracy: 0.7289
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5624 - accuracy: 0.7294
Epoch 5/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5589 - accuracy: 0.7294
Epoch 6/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5575 - accuracy: 0.7287
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5563 - accuracy: 0.7294
Epoch 8/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5553 - accuracy: 0.7297
Epoch 9/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5546 - accuracy: 0.7315
Epoch 10/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5535 - accuracy: 0.7308
Epoch 11/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5526 - accuracy: 0.7310
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5523 - accuracy: 0.7304
Epoch 13/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5515 - accuracy: 0.7310
Epoch 14/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5509 - accuracy: 0.7296
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5502 - accuracy: 0.7307
Epoch 16/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5497 - accuracy: 0.7312
Epoch 17/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5495 - accuracy: 0.7313
Epoch 18/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5492 - accuracy: 0.7311
Epoch 19/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5483 - accuracy: 0.7321
Epoch 20/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5485 - accuracy: 0.7322
Epoch 21/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5479 - accuracy: 0.7315
Epoch 22/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5474 - accuracy: 0.7313
Epoch 23/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5473 - accuracy: 0.7325
Epoch 24/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5472 - accuracy: 0.7327
Epoch 25/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5467 - accuracy: 0.7325
Epoch 26/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5465 - accuracy: 0.7334
Epoch 27/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5462 - accuracy: 0.7317
Epoch 28/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5460 - accuracy: 0.7324
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5457 - accuracy: 0.7333
Epoch 30/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5456 - accuracy: 0.7336
Epoch 31/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5448 - accuracy: 0.7334
Epoch 32/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5448 - accuracy: 0.7332
Epoch 33/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5444 - accuracy: 0.7344
Epoch 34/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5445 - accuracy: 0.7330
Epoch 35/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5443 - accuracy: 0.7336
Epoch 36/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5439 - accuracy: 0.7346
Epoch 37/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5438 - accuracy: 0.7348
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5435 - accuracy: 0.7349
Epoch 39/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5433 - accuracy: 0.7346
Epoch 40/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5436 - accuracy: 0.7341
Epoch 41/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5430 - accuracy: 0.7348
Epoch 42/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5426 - accuracy: 0.7354
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5425 - accuracy: 0.7355
Epoch 44/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5423 - accuracy: 0.7346
Epoch 45/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5420 - accuracy: 0.7354
Epoch 46/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5419 - accuracy: 0.7352
Epoch 47/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5421 - accuracy: 0.7358
Epoch 48/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5417 - accuracy: 0.7365
Epoch 49/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5413 - accuracy: 0.7355
Epoch 50/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5413 - accuracy: 0.7357
Epoch 51/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5411 - accuracy: 0.7355
Epoch 52/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5413 - accuracy: 0.7360
Epoch 53/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5408 - accuracy: 0.7362
Epoch 54/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5404 - accuracy: 0.7361
Epoch 55/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5404 - accuracy: 0.7364
Epoch 56/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5400 - accuracy: 0.7366
Epoch 57/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5401 - accuracy: 0.7364
Epoch 58/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5403 - accuracy: 0.7367
Epoch 59/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5399 - accuracy: 0.7358
Epoch 60/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5398 - accuracy: 0.7362
Epoch 61/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5395 - accuracy: 0.7369
Epoch 62/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5396 - accuracy: 0.7371
Epoch 63/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5393 - accuracy: 0.7362
Epoch 64/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5388 - accuracy: 0.7370
Epoch 65/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5393 - accuracy: 0.7378
Epoch 66/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5386 - accuracy: 0.7372
Epoch 67/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5386 - accuracy: 0.7357
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5383 - accuracy: 0.7371
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5386 - accuracy: 0.7377
Epoch 70/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5386 - accuracy: 0.7378
Epoch 71/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5386 - accuracy: 0.7367
Epoch 72/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5380 - accuracy: 0.7378
Epoch 73/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5381 - accuracy: 0.7363
Epoch 74/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5380 - accuracy: 0.7372
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5378 - accuracy: 0.7384
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5378 - accuracy: 0.7375
Epoch 77/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5378 - accuracy: 0.7384
Epoch 78/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5377 - accuracy: 0.7380
Epoch 79/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5377 - accuracy: 0.7376
Epoch 80/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5371 - accuracy: 0.7381
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5371 - accuracy: 0.7370
Epoch 82/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5370 - accuracy: 0.7379
Epoch 83/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5368 - accuracy: 0.7384
Epoch 84/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5368 - accuracy: 0.7385
Epoch 85/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7379
Epoch 86/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7383
Epoch 87/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7392
Epoch 88/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7381
Epoch 89/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7376
Epoch 90/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7376
Epoch 91/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7380
Epoch 92/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7382
Epoch 93/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7384
Epoch 94/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5363 - accuracy: 0.7394
Epoch 95/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7394
Epoch 96/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5357 - accuracy: 0.7391
Epoch 97/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5355 - accuracy: 0.7390
Epoch 98/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5356 - accuracy: 0.7392
Epoch 99/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5355 - accuracy: 0.7392
Epoch 100/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7385

In [28]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5577 - accuracy: 0.7300 - 587ms/epoch - 2ms/step
Loss: 0.5576581358909607, Accuracy: 0.7300291657447815